version: "3"
services:

    server:
        image: 23792803/newser_server:staging_18.11.2020
        container_name: server_newser
        restart: always
        volumes:
            - "/srv/logs/newser_server:/usr/src/app/logs"
        ports:
            - "5000:5000"
        environment:
            - SERVER_PORT=5000
            - RABBIT_USER=admin
            - RABBIT_PASSWORD=admin
            - RABBIT_HOST=10.19.19.4
            - RABBIT_PORT=5672
            - PG_USERNAME=postgres
            - PG_PASSWORD=12345678
            - PG_HOST=10.19.19.4
            - PG_PORT=35432
            - PG_DB=ias_db
            - QUERY_URL=http://10.19.19.4:1680/admin/give_search_query
            - DEFAULT_PAGES=1
            - SERVER_SOURCE=server
            - LOCAL_FILE_SOURCE=file
            - WEB_APP_SOURCE=web
            - PUPPETEER_QUEUE=puppeteer_bot
            - QUEUE_FILE=queries

    bot:
        image: 23792803/newser_bot:staging_18.11.2020
        restart: always
        volumes:
            - "/srv/logs/newser_bot:/usr/src/app/logs"
            - "/srv/logs/newser_server/cap_img:/usr/src/app/cap_img"
        environment:
            - ANTICAPTCHA_ID=97203e301632af0a78ff1ba36390b902
            - SERVER_PORT=5000
            - SERVER_HOST=server
            - DEFAULT_PAGES=1
            - SERVER_SOURCE=server
            - LOCAL_FILE_SOURCE=file
            - WEB_APP_SOURCE=web
            - PUPPETEER_QUEUE=puppeteer_bot
            - UNPROCESSED_QUEUE=news_unprocessed
            - QUEUE_FILE=queries
        links:
            - "server:server"
        depends_on: 
            - server

    # mercury:
    #     image: 23792803/newser_mercury:development_18.11.2020
    #     restart: always
    #     volumes:
    #         - "/srv/logs/newser_mercury:/usr/src/app/logs"
    #     environment:
    #         - RABBIT_HOST=10.19.19.4
    #         - RABBIT_PORT=5672
    #         - RABBIT_USER=admin
    #         - RABBIT_PASSWORD=admin
    #         - SERVER_HOST=server
    #         - SERVER_PORT=5000
    #         - QUEUE_FILE=queries
    #         - ERROR=news_error
    #         - PROCESSED=news_processed
    #         - UNPROCESSED=news_unprocessed
    #     links:
    #         - "server:server"
    #     depends_on:
    #         - server